---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.5.8
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: stage-binaries
  image: rancher/dapper:v0.5.8
  commands:
  - "cp -r ./bin/* ./package/"

- name: docker-publish-master
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "harbor.futuretea.me/rancher/harvester"
    registry: "harbor.futuretea.me"
    tag: ${DRONE_BRANCH}-head-amd64
    username:
      from_secret: docker_username

- name: docker-publish-webhook-master
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile.webhook
    password:
      from_secret: docker_password
    repo: "harbor.futuretea.me/rancher/harvester-webhook"
    registry: "harbor.futuretea.me"
    tag: ${DRONE_BRANCH}-head-amd64
    username:
      from_secret: docker_username

- name: docker-publish-upgrade-master
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
    context: package/upgrade
    custom_dns: 1.1.1.1
    dockerfile: package/upgrade/Dockerfile
    password:
      from_secret: docker_password
    repo: "harbor.futuretea.me/rancher/harvester-upgrade"
    registry: "harbor.futuretea.me"
    tag: ${DRONE_BRANCH}-head-amd64
    username:
      from_secret: docker_username

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest-master
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    target: "harbor.futuretea.me/rancher/harvester:${DRONE_BRANCH}-head"
    template: "harbor.futuretea.me/rancher/harvester:${DRONE_BRANCH}-head-ARCH"

- name: manifest-webhook-master
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    target: "harbor.futuretea.me/rancher/harvester-webhook:${DRONE_BRANCH}-head"
    template: "harbor.futuretea.me/rancher/harvester-webhook:${DRONE_BRANCH}-head-ARCH"

- name: manifest-upgrade-master
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    target: "harbor.futuretea.me/rancher/harvester-upgrade:${DRONE_BRANCH}-head"
    template: "harbor.futuretea.me/rancher/harvester-upgrade:${DRONE_BRANCH}-head-ARCH"

depends_on:
- amd64

---
kind: pipeline
name: build-iso

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.5.8
  commands:
  - dapper build-iso
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: upload_iso_release_master
  image: plugins/gcs
  settings:
    acl:
      - allUsers:READER
    cache_control: "public,no-cache,proxy-revalidate"
    source: dist/artifacts
    target: releases.rancher.com/harvester/master
    token:
      from_secret: google_auth_key

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

depends_on:
- manifest
